services:
  flask_app:
    build: 
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app:/app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped

  django_app:
    build:
      context: ./django_app
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    restart: unless-stopped 